name: smart_bites
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase (إصدارات متوافقة مع بعضها)
  firebase_core: ^3.12.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.3.10
  firebase_ui_database: ^1.5.0
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.0.1
  firebase_app_check: ^0.3.2+7
  shared_preferences: ^2.2.2

  # UI & Utilities
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_fortune_wheel: ^1.3.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^6.0.0
  rename: ^3.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

